import { addDoc } from 'firebase/firestore';
import { mailCol } from './schema';

/**
 * Trigger an email alert to the employee when leave request is approved or rejected
 * Uses Firebase's "Trigger Email" extension standard by writing to the 'mail' collection.
 */
export async function sendLeaveStatusEmailTrigger({
  employeeEmail,
  employeeName = 'Employee',
  status,
  startDate,
  endDate,
  days = 1,
  adminComment = '',
  leaveRequestId = '',
}) {
  if (!employeeEmail) {
    console.warn('No employee email provided for leave email alert trigger');
    return null;
  }

  const isApproved = (status || '').toLowerCase() === 'approved';
  const statusUpper = (status || 'reviewed').toUpperCase();
  const themeColor = isApproved ? '#10B981' : '#EF4444';
  const bgColor = isApproved ? '#ECFDF5' : '#FEF2F2';
  const textColor = isApproved ? '#065F46' : '#991B1B';

  const mailPayload = {
    to: [employeeEmail.trim()],
    message: {
      subject: `Dayflow HRMS: Leave Request ${statusUpper}`,
      text: `Hello ${employeeName},\n\nYour leave request from ${startDate} to ${endDate} (${days} day(s)) has been ${statusUpper} by HR Administration.\n\nHR Remarks: ${adminComment || 'None'}\n\nBest regards,\nDayflow HRMS Team`,
      html: `
        <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 28px; border: 1px solid #E2E8F0; border-radius: 12px; background: #FFFFFF;">
          <div style="text-align: center; margin-bottom: 24px;">
            <div style="display: inline-block; background: #6366F1; color: white; width: 44px; height: 44px; line-height: 44px; border-radius: 10px; font-size: 22px; font-weight: 800; text-align: center;">D</div>
            <h1 style="color: #0F0F23; margin: 12px 0 0 0; font-size: 22px; font-weight: 700;">Dayflow HRMS</h1>
            <p style="color: #64748B; font-size: 13px; margin: 2px 0 0 0;">Workforce Management Notification</p>
          </div>
          
          <div style="padding: 18px; border-radius: 10px; background: ${bgColor}; border-left: 4px solid ${themeColor}; margin-bottom: 24px;">
            <h2 style="color: ${textColor}; margin: 0 0 6px 0; font-size: 18px; font-weight: 700;">
              Leave Request ${statusUpper}
            </h2>
            <p style="margin: 0; color: #334155; font-size: 14px;">
              Hello <strong>${employeeName}</strong>, your leave application has been processed by the HR administration.
            </p>
          </div>

          <table style="width: 100%; border-collapse: collapse; font-size: 14px; margin-bottom: 24px;">
            <tbody>
              <tr style="border-bottom: 1px solid #F1F5F9;">
                <td style="padding: 10px 0; color: #64748B;">Duration:</td>
                <td style="padding: 10px 0; color: #1E293B; font-weight: 600; text-align: right;">${startDate} to ${endDate}</td>
              </tr>
              <tr style="border-bottom: 1px solid #F1F5F9;">
                <td style="padding: 10px 0; color: #64748B;">Total Days:</td>
                <td style="padding: 10px 0; color: #1E293B; font-weight: 600; text-align: right;">${days} ${Number(days) === 1 ? 'day' : 'days'}</td>
              </tr>
              <tr style="border-bottom: 1px solid #F1F5F9;">
                <td style="padding: 10px 0; color: #64748B;">Decision:</td>
                <td style="padding: 10px 0; color: ${themeColor}; font-weight: 700; text-align: right; text-transform: uppercase;">${status}</td>
              </tr>
              ${adminComment ? `
              <tr>
                <td style="padding: 10px 0; color: #64748B; vertical-align: top;">HR Note:</td>
                <td style="padding: 10px 0; color: #1E293B; text-align: right;">${adminComment}</td>
              </tr>` : ''}
            </tbody>
          </table>

          <div style="background: #F8FAFC; padding: 14px; border-radius: 8px; font-size: 13px; color: #475569; text-align: center; margin-bottom: 20px;">
            Log in to your Dayflow dashboard to view your updated leave balances and details.
          </div>

          <p style="font-size: 11px; color: #94A3B8; text-align: center; border-top: 1px solid #E2E8F0; padding-top: 16px; margin: 0;">
            This is an automated alert generated by Dayflow HRMS.
          </p>
        </div>
      `,
    },
    leaveRequestId: leaveRequestId || '',
    status: status,
    createdAt: new Date().toISOString(),
  };

  try {
    const docRef = await addDoc(mailCol, mailPayload);
    return { success: true, mailId: docRef.id, payload: mailPayload };
  } catch (err) {
    console.error('Failed to write email trigger doc to mail collection:', err);
    // Don't throw fatal error if mail trigger logging fails, but return error state
    return { success: false, error: err.message };
  }
}
